require "rake/testtask"

task :default => :test
Rake::TestTask.new do |t|
  # helper(simplecov) must be required before loading power_assert
  t.ruby_opts = ["-w"]
  t.test_files = FileList["test/*_test.rb"]
end
